concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "claudiu_lab_runner"
  url = "https://gitlab.com/"
  id = 29450630
  token = "glrt-5-hgcNT5yt8SAzR1WMhx"
  token_obtained_at = 2023-11-12T16:48:39Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "clau:1.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "clau_runner"
  url = "https://gitlab.com/"
  id = 29450921
  token = "glrt-zaGGu2PiGuSybqyHkCzo"
  token_obtained_at = 2023-11-12T17:31:14Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.cache]
    MaxUploadedArchiveSize = 0
